---

image: agalitsyn/goci:1.6

before_script:
  - export GITLAB_HOSTNAME="$(echo $CI_BUILD_REPO | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')"
  - export CURRENT_BUILD_PATH=$(pwd)
  - export PROJECT_REL_PATH="${CURRENT_BUILD_PATH#*/*/}"
  - export PROJECT_DIR=$GOPATH/src/$GITLAB_HOSTNAME/$PROJECT_REL_PATH

stages:
  - test

test:
  stage: test
  script:
    - mkdir -pv $PROJECT_DIR
    - cp -r $CURRENT_BUILD_PATH/* $PROJECT_DIR
    - cd $PROJECT_DIR
    - make test
  tags:
    - docker
