swagger: "2.0"
info:
  version: "1.0"
  title: "2GIS Пушер"
  contact:
    email: "lab@2gis.ru"
host: "localhost"
basePath: "/"
schemes:
- "http"
externalDocs:
  description: "Пушер в confluence"
  url: "https://confluence.2gis.ru/pages/viewpage.action?pageId=232885534"
paths:
  /readiness:
    get:
      tags:
      - "health"
      summary: "Готовность приложения"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "Готов"
        503:
          description: "Не готов"
  /1.0/devices:
    get:
      tags:
      - "devices"
      summary: "Получить список устройств пользователя"
      description: ""
      parameters:
      - name: "auth-token"
        in: "header"
        required: true
        type: "string"
        description: "Токен аутентификации, выданный сервисом аутентификации 2ГИС"
      produces:
      - "application/json"
      responses:
        200:
          description: "ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Device"
        500:
          description: "любой код ответа не равный 200"
          schema:
            $ref: "#/definitions/ErrResponse"

  /1.0/devices/{deviceId}:
    get:
      tags:
      - "devices"
      summary: "Получить устройство пользователя по ID"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "auth-token"
        in: "header"
        required: true
        type: "string"
        description: "Токен аутентификации, выданный сервисом аутентификации 2ГИС"
      - name: "deviceID"
        in: "path"
        description: "ID устройства"
        required: true
        type: "string"
      responses:
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/Device"
        500:
          description: "любой код ответа не равный 200"
          schema:
            $ref: "#/definitions/ErrResponse"
    put:
      tags:
      - "devices"
      summary: "Зарегистрировать новое устройство / обновить информацию об устройстве"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "auth-token"
        in: "header"
        required: true
        type: "string"
        description: "Токен аутентификации, выданный сервисом аутентификации 2ГИС"
      - name: "deviceID"
        in: "path"
        description: "ID устройства"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Device object"
        required: true
        schema:
          $ref: "#/definitions/Device"
      responses:
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/Device"
        500:
          description: "любой код ответа не равный 200"
          schema:
            $ref: "#/definitions/ErrResponse"
    delete:
      tags:
      - "devices"
      summary: "Удалить устройство"
      description: ""
      parameters:
      - name: "deviceID"
        in: "path"
        description: "ID устройства"
        required: true
        type: "string"
      responses:
        204:
          description: "deleted"
        500:
          description: "любой код ответа не равный 200"
          schema:
            $ref: "#/definitions/ErrResponse"
  /1.0/messages:
    post:
      tags:
      - messages
      summary: Отправить сообщение
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "x-auth-timestamp"
        in: "header"
        required: true
        type: "string"
        description: "Текущий unix timestamp клиента"
      - name: "x-client-id"
        in: "header"
        required: true
        type: "string"
        description: "Идентификатор клиента"
      - name: "x-signature"
        in: "header"
        required: true
        type: "string"
        description: "Подпись клиента"
      - in: "body"
        name: "body"
        description: "Message object"
        required: true
        schema:
          $ref: "#/definitions/MessageRequest"
      responses:
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/MessageResponse"
        500:
          description: "любой код ответа не равный 200"
          schema:
            $ref: "#/definitions/ErrResponse"
definitions:
  Device:
    type: "object"
    properties:
      id:
        type: "string"
        example: "550e8400-e29b-41d4-a716-44665544000"
        description: "Идентификатор устройства"
      token:
        type: "string"
        description: "Пуш-токен"
      platform:
        type: "string"
        enum:
        - "ios"
        - "android"
      model:
        type: "string"
        example: "Google Nexus 5"
        description: "Модель устройства"
      app_version:
        type: "string"
        example: "4.1.11.1698"
        description: "Версия приложения 2ГИС"
      user_id:
        type: "string"
      created_at:
        type: "string"
        format: "date-time"
        description: "unix timestamp"
        example: "1467008739804"
      updated_at:
        type: "string"
        format: "date-time"
        description: "unix timestamp"
        example: "1467008739804"
  MessageRequest:
    type: "object"
    properties:
      user_id:
        type: "string"
        description: "Или ID пользователя"
      device_ids:
        type: "array"
        items:
          type: "string"
        description: "Или ID девайсов"
      priority:
        type: "string"
        enum:
        - "normal"
        - "high"
        description: "Приоритет сообщения"
      content_available:
        type: "bool"
        example: true
      mutable_content:
        type: "bool"
        example: true
      time_to_live:
        type: "integer"
        example: 2419200
      data:
        type: "array"
        items:
          $ref: "#/definitions/MapItem"
      notification:
        $ref: "#/definitions/Notification"
  MessageResponse:
    type: "object"
    properties:
      devices_count:
        type: "integer"
        description: "На сколько девайсов сообщение было отправлено"
  ErrResponse:
    type: "object"
    properties:
      status:
        type: "string"
        description: "Код http статуса"
      error:
        type: "string"
        description: "Текст ошибки"
  MapItem:
    type: "object"
    properties:
      key:
        type: "string"
      value:
        type: "string"
  Notification:
    type: "object"
    properties:
      title:
        type: string
      body:
        type: string
      icon:
        type: string
      sound:
        type: string
      badge:
        type: integer
      tag:
        type: string
      color:
        type: string
      click_action:
        type: string
      body_loc_key:
        type: string
      body_loc_args:
        type: string
      title_loc_key:
        type: string
      title_loc_args:
        type: string
